### ISSUE TITLE
Trialページでのデータサイズ上限が小さい問題

### ISSUE THREAD

**Issue by zeki6** [tut-cc/SamurAI_Coding_2018-19_Practice_PageTemplates#10]
Trialページにて提出しようとしたファイルのサイズは1.16MB程度でしたが

> 413 Request Entity Too Large

と出て提出できません．
nginxの設定の問題だと思います．修正お願いします．

**Comment by arukuka** [comment]
報告ありがとうございます。
修正します。

**Comment by arukuka** [comment]
差し当たって昨年度を参考に 100 MB を受け付けるようにしました。
ご不便をおかけし申し訳ございません。

こちらで 60 MB 程度のデータを POST し、
trial.samuraicoding.info
提出が受け付けられることを確認しました。

**Comment by arukuka** [comment]
`compile.sh`, `run.sh` を含んだ 60 MB 程度のデータを提出し、  
ゲームが実施されることを確認しました。

@zeki6 締切直前となり大変恐縮ですが
ご確認ください。

**Comment by zeki6** [comment]
迅速な対応ありがとうございます．
提出が上手くいき，ゲーム結果まで確認できました．
